### ISSUE TITLE
mvn test: trying to connect to container at rabbit 

### ISSUE THREAD

**Issue by schadomi7** [hobbit-project/java-sdk-example#1]
While executing `mvn test`, execution halts at message:

`DEBUG [org.hobbit.sdk.docker.RabbitMqDockerizer] - <Trying to connect to container at rabbit (imageName=rabbitmq:latest)>`

System Info (tested on 3 different systems):
Ubuntu 17.10 VM, Docker version 1.13.1, build 092cba3
Fedora 26, Docker version 17.12.0-ce, build c97c6d6
boot2docker, Docker version 17.12.0-ce, build c97c6d6

Workaround:
Add `127.0.0.1 rabbit` or `<rabbit-container-ip> rabbit` to `/etc/hosts`.

**Comment by MichaelRoeder** [comment]
I think this line seems to cause the problem https://github.com/hobbit-project/java-sdk-example/blob/master/src/test/java/org/hobbit/sdk/examples/examplebenchmark/ExampleBenchmarkTest.java#L52 because it sets the rabbit host name to the default ("rabbit"). This should be `localhost` for Linux users and could be something else for Windows users. Denis implemented a functionality which can be reused at https://github.com/hobbit-project/core/blob/master/src/main/java/org/hobbit/utils/docker/DockerHelper.java#L34

@smirnp What do you think?

**Comment by smirnp** [comment]
By default the container deploys under the "rabbit" name and become attached to the 'hobbit' and 'hobbit-common' networks. 

You specify another hostname via calling the hostname() property for [builder](https://github.com/hobbit-project/java-sdk-example/blob/54aa972db7d687b91d406ec1a9dfd640fcc2abae/src/test/java/org/hobbit/sdk/examples/examplebenchmark/ExampleBenchmarkTest.java#L47) before it calls build()

**Comment by MichaelRoeder** [comment]
Well, you can solve it in that way as well. However, I thought that the example is created in a way that the user should be able to directly execute it. If that is the case you may want to add a comment that the user should set the host name for this test case or you use the docker helper method I linked above and try to get the docker address from the environment.

Or did I understood that wrong?

**Comment by smirnp** [comment]
@MichaelRoeder, you are correct. I will check how it behaves on fresh linux machine. I haven't faced such problem on my dev vm, where the platform was deployed before.

**Comment by smirnp** [comment]
I have tried specifying 'localhost'. It works for non-dockerized components, but dockerized components failed to connect rabbit at 'localhost', which looks logical. 

So workaround (add `127.0.0.1 rabbit` to `/etc/hosts`) looks as single working solution. 

Thank you for pointing it out, I will the update Readme accordingly.

**Comment by MichaelRoeder** [comment]
Maybe I misunderstand your test (it seems like you have edited it a lot since I had a look at it :smile: ) but wouldn't it be easier to change the [line](https://github.com/hobbit-project/java-sdk-example/blob/master/src/test/java/org/hobbit/sdk/examples/examplebenchmark/ExampleBenchmarkTest.java#L86)
```java
rabbitMqDockerizer = RabbitMqDockerizer.builder().build();
```
to something like
```java
RabbitMqDockerizer.Builder rabbitBuilder = RabbitMqDockerizer.builder();
if(!dockerized) {
    rabbitBuilder.hostName("localhost");
}
rabbitMqDockerizer = rabbitBuilder.build();
```
or
```java
RabbitMqDockerizer.Builder rabbitBuilder = RabbitMqDockerizer.builder();
if(!dockerized) {
    rabbitBuilder.hostName(DockerHelper.getHost());
}
rabbitMqDockerizer = rabbitBuilder.build();
```

**Comment by smirnp** [comment]
You are correct. But user still need to change it if he wants to run dockerized components. `mvn test` will also run both tests (non-dockerized and dockerized ones), where last will fail if config have not been changed. So it seems better to ask users to modify config before running tests.
